// quiz2.js — Ingliz tili (50) + Biologiya (50) + Kimyo (50) + Fizika (50)
Object.assign(quizBank, {
    "ingliz_tili": [
        { q: "'Software' o'zbek tarjimasi?", options: ["Qurilma", "Dastur", "Tarmoq", "Internet"], correct: 1, hint: "Programm = dastur" },
        { q: "'Knowledge' — o'zbek tarjimasi?", options: ["Kuch", "Bilim", "Imkoniyat", "Harakat"], correct: 1, hint: "Knowledge = bilim" },
        { q: "Noto'g'ri (Irregular) fe'l: Play, Work, Go, Look", options: ["Play", "Work", "Go", "Look"], correct: 2, hint: "Go → Went (o'zgargan shakl)" },
        { q: "'Debug' dasturlashda nima ma'nosi?", options: ["Yangi kod yozish", "Xatoni tuzatish", "O'chirish", "Saqlash"], correct: 1, hint: "Bug = xato, debug = xatoni topish" },
        { q: "'Deadline' — ma'nosi?", options: ["O'lik chiziq", "Topshirish muddati", "Boshlanish", "Dam olish"], correct: 1, hint: "Deadline = muddat oxiri" },
        { q: "'Brainstorming' nima?", options: ["Tahlil", "G'oyalar tufoni", "Mashg'ulot", "Muammo"], correct: 1, hint: "Brain=miya, storm=bo'ron → g'oyalar tufoni" },
        { q: "She ___ a doctor. (to be filling)", options: ["am", "is", "are", "be"], correct: 1, hint: "She/He/It → is" },
        { q: "'Teamwork' tarjimasi?", options: ["Yolg'iz ishlash", "Jamoaviy ish", "Loyiha", "Hamkorlik"], correct: 1, hint: "Team=jamoa, work=ish" },
        { q: "Past Simple: She (go) to school yesterday.", options: ["go", "goes", "went", "gone"], correct: 2, hint: "Go ning Past Simple = went" },
        { q: "'Approximately' so'zining ma'nosi?", options: ["Aniq", "Taxminan", "To'liq", "Mutlaqo"], correct: 1, hint: "Approximately = taxminan" },
        { q: "'I have been working for 3 hours' — qaysi zamon?", options: ["Present Simple", "Past Perfect", "Present Perfect Continuous", "Future"], correct: 2, hint: "Have been + V-ing = Present Perfect Continuous" },
        { q: "'Expand' antonimi?", options: ["Grow", "Increase", "Shrink", "Extend"], correct: 2, hint: "Expand = kengaytirish; aksi = Shrink (qisqarmoq)" },
        { q: "'The sun rises in the East' — qaysi zamon?", options: ["Past", "Present Simple", "Present Continuous", "Future"], correct: 1, hint: "Har doim ro'y beradigan holatlar → Present Simple" },
        { q: "Inglizcha 'Qancha?' = ?", options: ["What", "How much", "Where", "Why"], correct: 1, hint: "How much = qancha (sanalab bo'lmaydigan)" },
        { q: "'Curriculum' so'zining ma'nosi?", options: ["Darslik", "O'quv dasturi", "Sinf", "O'qituvchi"], correct: 1, hint: "Curriculum = o'quv reja yoki dastur" },
        { q: "'I will call you tomorrow' — necha gap turi?", options: ["So'roq", "Buyruq", "Oddiy", "Shart"], correct: 2, hint: "Oddiy tasdiqlash gapi." },
        { q: "'Artificial Intelligence' qisqartmasi = ?", options: ["AI", "IA", "AM", "AL"], correct: 0, hint: "A.I. = AI" },
        { q: "'Source code' nima?", options: ["Dastur kodi", "Veb-sayt", "Virus", "Ma'lumotlar bazasi"], correct: 0, hint: "Source code = dastur yozilgan kod" },
        { q: "'Algorithm' nima?", options: ["Matematik formula", "Muammo yechish qadamlari", "Dastur tili", "Xato"], correct: 1, hint: "Algorithm = bosqichma-bosqich ko'rsatmalar" },
        { q: "'Fluent in English' nima degani?", options: ["Inglizchani o'rganmoqda", "Inglizchani erkin biladi", "Inglizchaga qiziqadi", "Inglizcha o'qitadi"], correct: 1, hint: "Fluent = ravon, erkin" },
        { q: "He ___ read the book twice. (Present Perfect)", options: ["has", "have", "had", "is"], correct: 0, hint: "He/She/It → has + V3" },
        { q: "'Global warming' — o'zbek tarjimasi?", options: ["Global sovish", "Sayyoraviy isish", "Iqlim sovishi", "Kosmik o'zgarish"], correct: 1, hint: "Warming = isish" },
        { q: "'Synonym' nima?", options: ["Bir xil ma'nodagi so'z", "Qarama-qarshi so'z", "Yangi so'z", "Chet el so'zi"], correct: 0, hint: "Masalan: big = large = huge" },
        { q: "'Renewable energy' nima?", options: ["Qayta tiklanmaydigan energiya", "Qayta tiklanadigan energiya", "Yadro energiyasi", "Gaz energiyasi"], correct: 1, hint: "Renewable = qayta tiklanadigan" },
        { q: "'Prototype' so'zi texnologiyada nima ma'noni anglatadi?", options: ["Tayyor mahsulot", "Birinchi sinov namunasi", "Ishlab chiqarish liniyasi", "Savdo rejasi"], correct: 1, hint: "Prototype = dastlabki model" },
        { q: "'They are playing football now' — qaysi zamon?", options: ["Past", "Present Simple", "Present Continuous", "Future"], correct: 2, hint: "am/is/are + V-ing = Present Continuous" },
        { q: "'Feedback' so'zining ma'nosi?", options: ["Oldinga boqish", "Fikr-mulohaza berish", "Mahsulot", "Natija"], correct: 1, hint: "Feed=bermoq, back=orqaga → fikr qaytarish" },
        { q: "Inglizcha 'Qanday?' = ?", options: ["What", "When", "How", "Why"], correct: 2, hint: "How = qanday, qancha" },
        { q: "'Innovation' nima?", options: ["Eski usul", "Yangi g'oya yoki ixtiro", "Takrorlash", "Ko'chirish"], correct: 1, hint: "Innovate = yangilik kiriting" },
        { q: "'Potential' so'zining ma'nosi?", options: ["Haqiqiy", "Imkoniyat/salohiyat", "Muammo", "Qo'shimcha"], correct: 1, hint: "Potential = imkoniyat, kelajakdagi qobiliyat" },
        { q: "'Data' so'zi qo'llanilganda (ko'plik) = ?", options: ["is", "are", "was", "has"], correct: 1, hint: "Data (ko'plik) → are" },
        { q: "'I would like to...' — qo'llash joyi?", options: ["Buyruq berish", "Iltimos qilish", "Xabar berish", "Savol berish"], correct: 1, hint: "Would like = xohlamoqchiman (muloyim iltimos)" },
        { q: "'Efficiency' tarjimasi?", options: ["Samaradorlik", "Qiyinchilik", "Narx", "Tezlik"], correct: 0, hint: "Efficient = samarali" },
        { q: "'The project was completed on time' — qaysi shakl?", options: ["Active", "Passive", "Question", "Negative"], correct: 1, hint: "Was + V3 = Passive Voice" },
        { q: "'Ethics' so'zi qanday ma'no anglatadi?", options: ["Qonun", "Axloq normalari", "Texnik qoidalar", "Narx"], correct: 1, hint: "Ethics = axloq-odob normalari" },
        { q: "'He is as tall as his brother' — qanday taqqoslash?", options: ["Kattarlashtirilgan", "Teng darajali", "Eng yuqori daraja", "Yo'q"], correct: 1, hint: "As ... as = teng darajali taqqoslash" },
        { q: "'Communicate' so'zining ot shakli?", options: ["Communication", "Communicating", "Communicated", "Communicative"], correct: 0, hint: "-ion qo'shimchasi ot yasaydi" },
        { q: "'Schedule' so'zining ma'nosi?", options: ["Ish joyı", "Reja/jadval", "Maqsad", "Muammo"], correct: 1, hint: "Schedule = vaqt rejasi, jadval" },
        { q: "'Regardless of' iborasi nima ma'no anglatadi?", options: ["Sababli", "Qaramasdan", "Bilan birga", "Keyin"], correct: 1, hint: "Regardless of = ... ga qaramasdan" },
        { q: "'Collaborate' so'zining ma'nosi?", options: ["Raqobatlashmoq", "Hamkorlik qilmoq", "Tanqid qilmoq", "Almashtirmoq"], correct: 1, hint: "Co + labor = birgalikda ishlash" },
        { q: "'Vocabulary' nima?", options: ["Grammatika", "So'z boyligi", "Talaffuz", "Matn"], correct: 1, hint: "Vocabulary = biladigan so'zlar to'plami" },
        { q: "'If I were you, I would study harder' — qaysi shart?", options: ["Type 0", "Type 1", "Type 2", "Type 3"], correct: 2, hint: "Were + would = Type 2 (hayoliy shart)" },
        { q: "'Approximately 200 people attended' — 'approximately' o'rniga?", options: ["Exactly", "About", "Precisely", "Definitely"], correct: 1, hint: "About = taxminan" },
        { q: "'Conclude' so'zidan ot yasang:", options: ["Conclusive", "Conclusion", "Concluding", "Concluded"], correct: 1, hint: "-ion qo'shimchasi ko'pincha ot yasaydi" },
        { q: "'Diverse' so'zining antonimi?", options: ["Different", "Varied", "Uniform", "Multiple"], correct: 2, hint: "Diverse = xilma-xil; aksi = Uniform (bir xil)" },
        { q: "'I haven't seen him since Monday' — konstruktsiya nima?", options: ["Past Simple", "Present Perfect", "Past Perfect", "Future"], correct: 1, hint: "Haven't + V3 + since → Present Perfect" },
        { q: "'Challenge' so'zining ma'nosi?", options: ["Oson vazifa", "Qiyinlik/sinovli vazifa", "Muvaffaqiyat", "Dam olish"], correct: 1, hint: "Challenge = qiyin vazifa, sinov" },
        { q: "'Launch' texnologiyada nima degani?", options: ["Samolyot", "Mahsulot yoki dasturni chiqarish", "Test qilish", "Sotish"], correct: 1, hint: "Launch = rasman ishga tushirish" },
        { q: "'Transparent' figurativ (ko'chma) ma'noda?", options: ["Shaffof", "Ochiq va yashirin joyi yo'q", "Rang-barang", "Tez"], correct: 1, hint: "Ochiq, yashirin bo'lmagan → transparent kompaniya" }
    ],
    "biologiya": [
        { q: "Odam qonidagi eng ko'p hujayra turi?", options: ["Oq qon tanachalari", "Trombositlar", "Qizil qon tanachalari", "Plazma"], correct: 2, hint: "Ular O₂ tashiydi." },
        { q: "Hujayraning quvvat manbai?", options: ["Yadro", "Mitoxondriya", "Sitoplazma", "Ribosoma"], correct: 1, hint: "Mitoxondriya = 'elektr stansiyasi'" },
        { q: "Odam organizmidagi eng katta a'zo?", options: ["Jigar", "O'pka", "Teri", "Miyak"], correct: 2, hint: "Teri tana yuzasini qoplaydi." },
        { q: "DNK nima?", options: ["Dori nomi", "Irsiy ma'lumot molekulasi", "Oqsil turi", "Gormon"], correct: 1, hint: "Irsiyat va hujayra dasturi." },
        { q: "Yurak necha kameradan iborat?", options: ["2", "3", "4", "5"], correct: 2, hint: "2 bo'lmacha + 2 qorincha = 4" },
        { q: "Fotosintez qaysi organoidda amalga oshadi?", options: ["Mitoxondriya", "Xloroplast", "Yadro", "Lizosoma"], correct: 1, hint: "Xlorofil xloroplastda bor." },
        { q: "O'simliklar quyosh energiyasini qanday energiyaga aylantiradi?", options: ["Kimyoviy", "Issiqlik", "Mexanik", "Elektr"], correct: 0, hint: "Fotosintez → kimyoviy energiya" },
        { q: "Qon guruhlari necha xil?", options: ["2", "3", "4", "5"], correct: 2, hint: "A, B, AB, O — 4 ta guruh." },
        { q: "Odam miyasining eng katta qismi?", options: ["Miyacha", "Miya ustuni", "Katta yarim sharlar", "Gippokamp"], correct: 2, hint: "Katta yarim sharlar = tafakkur markazi." },
        { q: "O'simlik hujayrasini hayvon hujayrasidan farqi?", options: ["Mitoxondriya yo'q", "Hujayra devori bor", "Yadro yo'q", "Ribosoma yo'q"], correct: 1, hint: "Hujayra devori va xloroplast — o'simlik belgisi." },
        { q: "Urug'lanish qayerda amalga oshadi?", options: ["Bachadon", "Tuxumdon", "Nay(tuba)", "Siydik pufagi"], correct: 2, hint: "Fallopiy nayi — urug'lanish joyi." },
        { q: "Odam ustunchasining vazifasi?", options: ["Ovqat hazm qilish", "Tana holatini saqlab turish", "O'sish", "Qon tashish"], correct: 1, hint: "Umurtqa pog'onasi = tayanch va himoya." },
        { q: "Neyron nima?", options: ["Qon hujayra", "Asab hujayra", "Muskul hujayra", "Suyak hujayra"], correct: 1, hint: "Asab tizimi neyronlardan tashkil topgan." },
        { q: "Insulin qayerda ishlab chiqariladi?", options: ["Jigar", "Me'da osti bezi", "Buyrak", "O'pka"], correct: 1, hint: "Pankreas → insulin gormonı." },
        { q: "Bakteriyalar qanday organizmlar?", options: ["Ko'p hujayrali", "Bir hujayrali eukariot", "Bir hujayrali prokariot", "Virus"], correct: 2, hint: "Prokariot = yadro yo'q." },
        { q: "Inson DNK si qayerda saqlanadi?", options: ["Mitoxondriya", "Sitoplazma", "Yadro", "Ribosoma"], correct: 2, hint: "Asosiy DNK yadro xromasomalarida." },
        { q: "Qon aylanish doiralari nechtа?", options: ["1", "2", "3", "4"], correct: 1, hint: "Kichik va katta doira." },
        { q: "O'sish gormoni qayerda ishlab chiqariladi?", options: ["Qalqonsimon bez", "Gipofiz", "Buyrak usti bezi", "Me'da osti bezi"], correct: 1, hint: "Gipofiz = bosh boshqaruvchi bez." },
        { q: "Baliqlar qanday nafas oladi?", options: ["O'pka", "Teri orqali", "Jabra", "Ikkalasi"], correct: 2, hint: "Jabra suvdan O₂ ajratadi." },
        { q: "Hujayraning 'fabrikasi' — oqsillar ishlab chiqaruvchi organoid?", options: ["Mitoxondriya", "Ribosoma", "Lizosoma", "Sentrosoma"], correct: 1, hint: "Ribosoma = oqsil sintezi joyi." },
        { q: "Irsiyat qonunlarini kim kashf etgan?", options: ["Darvin", "Mendel", "Paster", "Nyuton"], correct: 1, hint: "Gregor Mendel — genetika otasi." },
        { q: "Biologik evolyutsiya nazariyasini kim yaratgan?", options: ["Mendel", "Lamarck", "Darvin", "Fleming"], correct: 2, hint: "Charlz Darvin — tabiiy tanlanish nazariyasi." },
        { q: "Penitsillin antibiotiгini kim kashf etgan?", options: ["Koch", "Darvin", "Fleming", "Paster"], correct: 2, hint: "Aleksandr Fleming — 1928 yil." },
        { q: "O'simliklar uchun asosiy oziqlanish manbayi?", options: ["Azot", "Karbonat angidrit + suv + quyosh", "Kislorod", "Mineral tuzlar"], correct: 1, hint: "Fotosintez uchun CO₂ + H₂O + nur kerak." },
        { q: "Qaysi vitamin D ning manbai?", options: ["Sut", "Quyosh nuri", "Sabzavot", "Go'sht"], correct: 1, hint: "Quyosh nuri terida D vitamini hosil qiladi." },
        { q: "Odam organizmi suvning necha foizidan iborat?", options: ["30%", "50%", "60-70%", "90%"], correct: 2, hint: "Kattalar tanasining 60-70% suv." },
        { q: "Hujayra bo'linishining asosiy turi?", options: ["Mitoz", "Mejoz", "Amitoz", "Apoptoz"], correct: 0, hint: "Mitoz = barabеr bo'linish, ko'payish." },
        { q: "Oq qon tanachalari (leykositlar) vazifasi?", options: ["O₂ tashish", "Qon ivitish", "Immunitet", "Moddalar almashinuvi"], correct: 2, hint: "Leykositlar infeksiyaga qarshi kurashadi." },
        { q: "Ekosistemada eng asosiy energiya manbai?", options: ["Suv", "Tuproq", "Quyosh", "Havo"], correct: 2, hint: "Barcha tirik mavjudotlar uchun quyosh — birlamchi manba." },
        { q: "Viruslar tirik mavjudotmi?", options: ["Ha", "Yo'q", "Ba'zan", "Atrof-muhitga bog'liq"], correct: 1, hint: "Viruslar hujayrasiz bo'lgani uchun 'tirik' deb hisoblanmaydi." },
        { q: "O'simliklarning suv va mineral tuzlarni o'troq qiluvchi tizim?", options: ["Floema", "Ksilema", "Meristema", "Korteks"], correct: 1, hint: "Ksilema — suv tashuvchi" },
        { q: "Adaptatsiya nima?", options: ["Turning yo'qolishi", "Organizmning muhitga moslashishi", "Ovqat yeyish", "Harakatlanish"], correct: 1, hint: "Evolutsion moslashuv = adaptatsiya." },
        { q: "Qanday organizm parazit deb ataladi?", options: ["Boshqa organizmlar hisobiga yashovchi", "Foydali organizm", "O'simlik", "Bakteriya"], correct: 0, hint: "Parazit = boshqaning zarariga yashaydi." },
        { q: "Antigen va antitelo o'rtasidagi munosabat?", options: ["Antigen = dori", "Antitelo antigenni zararsizlantiradi", "Teskari", "Bir xil narsa"], correct: 1, hint: "Antitelo immunitet tizimi mahsuli." },
        { q: "Qaysi a'zo qon tozalash vazifasini bajaradi?", options: ["O'pka", "Jigar", "Buyrak", "Yurak"], correct: 2, hint: "Buyrak siydik orqali chiqindini chiqaradi." },
        { q: "Qanday organizm mutualizm munosabatida yashaydi?", options: ["Ikkalasi zararlanadi", "Biri foyda, ikkinchisi zarar ko'radi", "Ikkalasi ham foyda ko'radi", "Biri befarq"], correct: 2, hint: "Mutualizm = o'zaro foyda." },
        { q: "Hujayra membranasining asosiy vazifasi?", options: ["Oqsil sintezi", "Energiya ishlab chiqarish", "Moddalarni o'tkazish va himoya", "Genetik ma'lumot"], correct: 2, hint: "Selektiv o'tkazuvchan qatlam." },
        { q: "Fotosintezda qaysi gaz ajralib chiqadi?", options: ["CO₂", "H₂O", "O₂", "N₂"], correct: 2, hint: "O'simliklar kislorod chiqaradi." },
        { q: "Asosiy azot a'zosi qaysi?", options: ["O'pka", "Ichak", "Buyrak", "Jigar"], correct: 2, hint: "Siydik kislotasi buyrak orqali chiqariladi." },
        { q: "Qaysi hujayralar qon ivitishini ta'minlaydi?", options: ["Eritrotsit", "Leykosit", "Trombosit", "Limfosit"], correct: 2, hint: "Trombositlar qon laxtасini hosil qiladi." },
        { q: "Odam umurtqa pog'onaсi necha umurtqadan iborat?", options: ["24", "28", "33", "40"], correct: 2, hint: "Bo'yin 7, ko'krak 12, bel 5, dum 9 ≈ 33." },
        { q: "Inson eshtish a'zosi?", options: ["Ko'z", "Ko'krak", "Quloq", "Burun"], correct: 2, hint: "Quloq to'lqinlarni his etadi." },
        { q: "Qanday energiya manbayi asosan muskullarda ishlatiladi?", options: ["Oqsil", "Vitamin", "ATP", "DNK"], correct: 2, hint: "ATP = adenozin trifosfat = energiya 'puli'" },
        { q: "Qaysi organ qon ishlab chiqarishda ishtirok etadi?", options: ["Jigar", "Suyak ko'migi", "Buyrak", "Taloq"], correct: 1, hint: "Suyak ko'migi — qon hosil bo'lish joyi." },
        { q: "Trofik zanjirda birinchi bo'g'in?", options: ["Yirtqich", "O'simlikxo'r", "O'simlik", "Zamburug'"], correct: 2, hint: "Ishlab chiqaruvchi = oʻsimlik." },
        { q: "Inson organizmida nechtа xromasoma bor?", options: ["23", "46", "44", "48"], correct: 1, hint: "23 juft = 46 ta xromasoma." },
        { q: "Immunitet nima?", options: ["Kasallik", "Organizmning himoya tizimi", "Vitamin", "Dori"], correct: 1, hint: "Immunitet xorijiy zarrachalardan himoya qiladi." },
        { q: "Ferment nima?", options: ["Oqsil katalizatori", "Yog'", "Karbonsuvod", "Mineral"], correct: 0, hint: "Fermentlar (enzimlar) — biologik katalizatorlar." },
        { q: "Eng kichik hujayrаlar qaysi?", options: ["Asab", "Muskul", "Eritrotsit", "Trombosit"], correct: 3, hint: "Trombositlar juda kichik (2-4 mkm)." }
    ],
    "kimyo": [
        { q: "Suvning kimyoviy formulasi?", options: ["CO₂", "H₂O", "O₂", "H₂O₂"], correct: 1, hint: "2 vodorod + 1 kislorod atomi." },
        { q: "Mendeleyev jadvalidagi birinchi element?", options: ["Kislorod", "Geliy", "Vodorod", "Azot"], correct: 2, hint: "H = Vodorod, tartib raqami 1." },
        { q: "Neytral muhitning pH qiymati?", options: ["0", "7", "14", "5"], correct: 1, hint: "Kislotali < 7 < Ishqoriy." },
        { q: "Fotosintez uchun zarur gaz?", options: ["O₂", "N₂", "CO₂", "H₂S"], correct: 2, hint: "O'simliklar CO₂ yutadi." },
        { q: "NaCl — bu nima?", options: ["Suv", "Osh tuzi", "Spirt", "Kislota"], correct: 1, hint: "Natrium xlorid = oddiy osh tuzi." },
        { q: "H₂SO₄ — bu nima?", options: ["Xlorid kislota", "Nitrat kislota", "Sulfat kislota", "Fosfor kislota"], correct: 2, hint: "Sulfur + kislorod + vodorod = sulfat kislota." },
        { q: "Oksid nima?", options: ["Kislorod bilan qo'shilish", "Metall parchalanishi", "Kislota hosil bo'lishi", "Tuz eritilishi"], correct: 0, hint: "Oksidlanish = kislorod bilan reaksiya." },
        { q: "Olmos va grafit qaysi elementning allotropiya shakllari?", options: ["Azot", "Kislorod", "Uglerod", "Kremniy"], correct: 2, hint: "C (uglerod) — olmos va grafitni hosil qiladi." },
        { q: "Qaysi gas yonadi va portlaydi?", options: ["CO₂", "N₂", "H₂", "O₂"], correct: 2, hint: "Vodorod — yonuvchi va portlovchi." },
        { q: "Elementlar davriy jadvalini kim tuzdirgan?", options: ["Kirxi", "Mendeleyev", "Dalton", "Lavuaze"], correct: 1, hint: "Dmitriy Mendeleyev — 1869 yil." },
        { q: "Kauchuk (rezina) qanday moddadan olinadi?", options: ["Neft", "Kauchuk daraxti shirasi", "Sellyuloza", "Shakar"], correct: 1, hint: "Natural kauchuk = Hevea daraxtidan." },
        { q: "Kislota va asosning reaksiyasi natijasi?", options: ["Yangi kislota", "Oksid", "Tuz va suv", "Metall"], correct: 2, hint: "Neytrallash reaksiyasi → tuz + H₂O" },
        { q: "Elektrdan tok o'tishi natijasida suv parchalansa, hоsil bo'ladi?", options: ["CO₂ va N₂", "H₂ va O₂", "NaCl va suv", "Hech narsa"], correct: 1, hint: "Elektroliz: 2H₂O → 2H₂ + O₂" },
        { q: "Polimer nima?", options: ["Oddiy molekula", "Ko'p takrorlanuvchi bo'g'inli zanjir", "Metall", "Kislota"], correct: 1, hint: "Polimer = poli (ko'p) + mer (bo'g'in)" },
        { q: "Kimyoviy formulada H₂O₂ nima?", options: ["Suv", "Vodorod peroksid", "Havoda kislorod", "Gidrogen"], correct: 1, hint: "H₂O₂ = vodorod peroksid (oksidlovchi)." },
        { q: "Qaysi metall eng yengil?", options: ["Temir", "Mis", "Litiy", "Alyuminiy"], correct: 2, hint: "Li — eng past zichlıkli metall." },
        { q: "Toza oltin qanday karatda bo'ladi?", options: ["14 karat", "18 karat", "24 karat", "10 karat"], correct: 2, hint: "24 karat = 100% toza oltin." },
        { q: "Organik kimyo nima o'rganadi?", options: ["Metallarni", "Uglerod birikmalarini", "Kislotalarni", "Tuzlarni"], correct: 1, hint: "Organik = uglerodli birikmalar." },
        { q: "Ozon formulasi?", options: ["O₂", "O₃", "CO", "NO"], correct: 1, hint: "Ozon = 3 ta kislorod atomi." },
        { q: "Qaysi gaz nafas olishda foydalanamiz?", options: ["CO₂", "N₂", "O₂", "Ar"], correct: 2, hint: "Kislorod (O₂) havo tarkibining ~21%." },
        { q: "Mis necha valentlilikka ega?", options: ["Faqat 1", "1 va 2", "2 va 3", "Faqat 3"], correct: 1, hint: "Cu(I) va Cu(II) — ikki xil holat." },
        { q: "Alyuminiy oksidining kimyoviy formulasi?", options: ["AlO", "Al₂O", "Al₂O₃", "AlO₂"], correct: 2, hint: "Alyuminiy valentligi 3, kislorod 2: Al₂O₃." },
        { q: "Kimyoviy tenglama muvozanat qonuni nimani ko'rsatadi?", options: ["Reaksiya tezligi", "Atom sonining saqlanuvi", "Energiya miqdori", "Temperaturа"], correct: 1, hint: "Massa saqlanuv qonuni: hech narsa yo'qolmaydi." },
        { q: "Qaysi modda oksidlovchi agent sifatida ishlaydi?", options: ["H₂", "Na", "O₂", "Fe"], correct: 2, hint: "O₂ boshqalarning elektronlarini oladi." },
        { q: "Fenolftaleyn ishqor muhitida qanday rangga kiradi?", options: ["Ko'k", "Sariq", "Qizil", "Rangsiz"], correct: 2, hint: "Ishqorli muhit → qirmizi rang." },
        { q: "Qaysi element yarim o'tkazgich?", options: ["Temir", "Silitsiy", "Mis", "Oltin"], correct: 1, hint: "Si (Silitsiy) — kremniy, elektronika asosi." },
        { q: "Benzolning molekulyar formulasi?", options: ["C₂H₄", "C₆H₆", "C₆H₁₂", "C₄H₈"], correct: 1, hint: "Benzol = 6 ta C va 6 ta H." },
        { q: "Vodorodning valentligi?", options: ["0", "1", "2", "3"], correct: 1, hint: "H doimo 1 valentli." },
        { q: "Titrlash kimyoda nima vazifasini o'taydi?", options: ["Reaksiya tezligi", "Konsentratsiyani aniqlash", "Haroratni o'lchash", "Rang berish"], correct: 1, hint: "Titrash = eritmaning konsentilasiyasini aniqlash usuli." },
        { q: "Neft asosan nimadan iborat?", options: ["Mineral tuzlar", "Uglerodli birikmalar (uglevodorodlar)", "Metallar", "Suv"], correct: 1, hint: "Neft = uglevodorodlar aralashmasi." },
        { q: "Temir zanglamasi qanday reaksiya?", options: ["Qaytarilish", "Oksidlanish", "Almashtirish", "Parchalanish"], correct: 1, hint: "4Fe + 3O₂ + 6H₂O → 4Fe(OH)₃" },
        { q: "Qaysi kislota eng kuchli deb hisoblanadi?", options: ["Sirka kislota", "Xlorid kislota", "Sulfat kislota", "Nitrat kislota"], correct: 2, hint: "H₂SO₄ eng kuchli oksidlovchi kislota." },
        { q: "Davriy jadvalda elementlar qanday tartibda joylashgan?", options: ["Harflar bo'yicha", "Tartib raqami (proton soni) bo'yicha", "Og'irligi bo'yicha", "Rangi bo'yicha"], correct: 1, hint: "Atom raqami = proton soni." },
        { q: "Gaz holati → suyuq holat o'tishi qanday deyiladi?", options: ["Bug'lanish", "Suyuqlanish", "Kondensatsiya", "Kristallanish"], correct: 2, hint: "Gaz → suyuq = kondensatsiya." },
        { q: "Qaysi element Yer po'stlog'ida eng ko'p uchraydi?", options: ["Alyuminiy", "Kislorod", "Silitsiy", "Temir"], correct: 1, hint: "O₂ — ~46% Yer po'stining massasida." },
        { q: "Mole (mol) kimyoda nima?", options: ["Og'irlik birligi", "6.022×10²³ zarrachalar soni", "Hajm birligi", "Temperatura birligi"], correct: 1, hint: "1 mol = Avogadro soni = 6.022×10²³" },
        { q: "Limon kislotasi formulasi?", options: ["C₂H₂O₄", "C₆H₈O₇", "CH₃COOH", "HCl"], correct: 1, hint: "Limon kislotasi — sitron kislota." },
        { q: "Qaysi harоrat suvning qaynash nuqtasi (1 atm)?", options: ["90°C", "100°C", "110°C", "150°C"], correct: 1, hint: "Dengiz sathida 100°C." },
        { q: "Qaysi element havoda eng ko'p?", options: ["Kislorod", "Vodorod", "Azot", "Argon"], correct: 2, hint: "N₂ — havoning ~78%." },
        { q: "Sublimatsiya nima?", options: ["Suyuq → gaz", "Qattiq → gaz (suyuq holatni chetlab)", "Gaz → qattiq", "Suyuq → qattiq"], correct: 1, hint: "Qoʻrgʻoshin qoraligi: qattiqdan gaz — sublimatsiya." },
        { q: "Qaysi kislota oshqozonda hamid? (hazm kislotasi)", options: ["Sulfat", "Xlorid", "Sirka", "Limon"], correct: 1, hint: "HCl = xlorid kislota — me'da shirasi." },
        { q: "Qaysi modda umumiy antiseptik?", options: ["Etanol (spirt)", "Suv", "Tuz", "Yog'"], correct: 0, hint: "Etanol 70% = antiseptik." },
        { q: "Qaysi metall simob bilan birlashib amalgam hosil qiladi?", options: ["Natriy", "Oltin", "Temir", "Mis"], correct: 1, hint: "Oltin-simob amalgami mashhur." },
        { q: "Endotermik reaksiya nima?", options: ["Issiqlik ajratada", "Issiqlik yutadi", "Nur ajratada", "Gaz ajratadi"], correct: 1, hint: "Endo (ichga) = issiqlik yutadi." },
        { q: "Plastmassa qanaqa modda?", options: ["Metall", "Polimer", "Mineral", "Biologik modda"], correct: 1, hint: "Plastik = sintetik polimer." },
        { q: "Elektronegatifliği eng yuqori element?", options: ["Kislorod", "Ftor", "Xlor", "Azot"], correct: 1, hint: "F (Ftor) — eng elektronegatif element." },
        { q: "Qaysi gaz havodan og'irroq?", options: ["H₂", "He", "CO₂", "CH₄"], correct: 2, hint: "CO₂ = 44 g/mol, havo ≈ 29 g/mol" },
        { q: "Tuz eritmasining pH qanday bo'lishi mumkin?", options: ["Doim 7", "7 dan katta ham, kichik ham", "Doim 7 dan katta", "Doim 7 dan kichik"], correct: 1, hint: "Kuchli kislota tuzi — kislotali; kuchli asos tuzi — ishqoriy." },
        { q: "Kimyoviy reaksiyada katalizator nima qiladi?", options: ["Reaksiyaga kiradi", "Reaksiya tezligini oshiradi, o'zi o'zgarmaydi", "Energiya beradi", "Reaksiyani to'xtatadi"], correct: 1, hint: "Katalizator = reaksiyani tezlashtiruvchi, sarflanmaydi." }
    ],
    "fizika": [
        { q: "Nyutonning birinchi qonuni nima?", options: ["F = ma", "Har ta'sirga teng qarata-tion bor", "Jism ta'sir bo'lmasa doimiy harakat qiladi", "Energiya saqlanadi"], correct: 2, hint: "Inersiya qonuni — tashqi kuch bo'lmasa holat o'zgarmaydi." },
        { q: "Yorug'lik tezligi taxminan qancha?", options: ["3×10⁸ m/s", "3×10⁶ m/s", "3×10⁵ km/h", "3×10⁴ m/s"], correct: 0, hint: "c = 300,000 km/s" },
        { q: "Ohm qonuni: U = ?", options: ["R/I", "I×R", "I×P", "R×P"], correct: 1, hint: "Kuchlanish = tok × qarshilik" },
        { q: "Energiya birligi SI sistemasida?", options: ["Vatt", "Nyuton", "Joul", "Paskal"], correct: 2, hint: "J = Joul = N·m" },
        { q: "Qattiq jismning erish nuqtasida temperatura qanday o'zgaradi?", options: ["Oshadi", "Pasayadi", "O'zgarmaydi", "Tez oshadi"], correct: 2, hint: "Faza o'tishida temperatura doimiy." },
        { q: "Elektr toki o'lchash birligi?", options: ["Volt", "Amper", "Om", "Vatt"], correct: 1, hint: "A = Amper (I)." },
        { q: "Qaysi to'lqin zarrachalar ishtirokisiz tarqalishi mumkin?", options: ["Mexanik to'lqin", "Elektromagnit to'lqin", "Tovush to'lqini", "Suv to'lqini"], correct: 1, hint: "Yorug'lik — elektromagnit; vakuumda tarqaladi." },
        { q: "Nyutonning uchinchi qonuni?", options: ["F=ma", "Inersiya", "Har ta'sirga teng va qarama-qarshi reaksiya", "Energiya saqlanadi"], correct: 2, hint: "Harakat va aks-harakat." },
        { q: "Gravitatsiya tortishish qonunini kim kashf etgan?", options: ["Eynshteyn", "Galiley", "Nyuton", "Faraday"], correct: 2, hint: "Nyuton olmasi afsonasi." },
        { q: "Elektromagnit induksiya kashf etgan olim?", options: ["Amper", "Om", "Faraday", "Tesla"], correct: 2, hint: "Maykl Faradey — 1831 yil." },
        { q: "Ish quvvati formulasi?", options: ["P = F×t", "P = W/t", "P = U×R", "P = m×v"], correct: 1, hint: "Quvvat = ish / vaqt" },
        { q: "Suyuqlik bosimi formulasi?", options: ["P = m×g", "P = ρ×g×h", "P = F/S", "P = W/V"], correct: 1, hint: "Gidrostatik bosim: ro × g × h" },
        { q: "Yer gravitatsiyasi (g) taxminan qancha?", options: ["8 m/s²", "9.8 m/s²", "10.5 m/s²", "11 m/s²"], correct: 1, hint: "g ≈ 9.8 m/s² (taxminan 10 ishlatiladi)" },
        { q: "Issiqlik simlari qanday ishlaydi?", options: ["O'tkazuvchanlik", "Konveksiya", "Radiatsiya", "Barchasi"], correct: 0, hint: "Qattiq jismlarda issiqlik o'tkazuvchanlik orqali." },
        { q: "Qaysi rang yorug'likning eng qisqa to'lqin uzunligiga ega?", options: ["Qizil", "Sariq", "Ko'k", "Binafsha"], correct: 3, hint: "Binafsha ≈ 380nm — eng qisqa." },
        { q: "Linza kuchini o'lchash birligi?", options: ["Dioptriya", "Lyuks", "Om", "Gerc"], correct: 0, hint: "1 D = 1/f (f metrda)" },
        { q: "Atom yadrosi nimadan iborat?", options: ["Elektron va proton", "Proton va neytron", "Proton faqat", "Neytron faqat"], correct: 1, hint: "Yadro = proton + neytron." },
        { q: "Elektron zaryadi qanday?", options: ["Musbat", "Manfiy", "Neytral", "O'zgaruvchan"], correct: 1, hint: "Elektron manfiy zaryadli (−e)." },
        { q: "Tovush tezligi havoda taxminan?", options: ["340 m/s", "3000 m/s", "3×10⁸ m/s", "100 m/s"], correct: 0, hint: "Havoda ≈ 343 m/s." },
        { q: "Magnit maydonida harakat qilayotgan zaryadlangan zarrachaga ta'sir etuvchi kuch?", options: ["Amper kuchi", "Lorents kuchi", "Kulонov kuchi", "Gravitatsiya"], correct: 1, hint: "Lorents kuchi = zaryadlangan zarrachaga magnit kuchi." },
        { q: "Termodinamikaning birinchi qonuni nima?", options: ["Issiqlik yo'qolmaydi", "Energiya saqlanadi va алмашинади", "Efficiенsi 100% da mumkin", "Entropiya kamayadi"], correct: 1, hint: "Energiya saqlanishi qonuni." },
        { q: "Kinetik energiya formulasi?", options: ["E = mgh", "E = ½mv²", "E = F×d", "E = Pt"], correct: 1, hint: "KE = yo'lovchi massa × tezlik² / 2" },
        { q: "Potensial energiya formulasi (gravitatsion)?", options: ["E = ½mv²", "E = mgh", "E = P×t", "E = kx²"], correct: 1, hint: "PE = massa × g × balandlik" },
        { q: "Foton nima?", options: ["Elektron", "Yorug'lik kvanti", "Proton", "Neytron"], correct: 1, hint: "Foton — yorug'likning zarracha holati." },
        { q: "Yadro reaksiyasida qanday energiya ajraladi?", options: ["Kimyoviy", "Mexanik", "Yadroviy", "Gravitatsion"], correct: 2, hint: "E = mc² (massa energiyaga aylanadi)." },
        { q: "Silindr shaklidagi idishda suyuqlik bosimi nechinchisiga bog'liq?", options: ["Suyuqlik hajmiga", "Idish shaklga", "Balandlikka", "Idish kesimiga"], correct: 2, hint: "P = ρgh — faqat balandlikka bog'liq." },
        { q: "Qaysi jarayon qaytmas?", options: ["Elastik zарb", "Muz erishi", "Ko'proq entropiyali jarayon", "Ideal gaz kengayishi"], correct: 2, hint: "Entropiya oshishi — termodinamikaning 2-qonuni." },
        { q: "Transformatorning asosiy vazifasi?", options: ["Tok kuchini oshirish", "Kuchlanishni o'zgartirish", "Energiya saqlamoq", "Tok yo'nalishini almashtirish"], correct: 1, hint: "Transformator kuchlanishni oshiradi yoki kamaytiradi." },
        { q: "Interferensiya nima?", options: ["Yorug'likning sinishi", "Ikki to'lqinning superpositsiyasi", "Yorug'likning qaytarилishi", "Dispersiya"], correct: 1, hint: "To'lqinlar o'zaro ta'siridan kuchaytirish yoki so'ndrish." },
        { q: "Kvant mexanikasini asoslagan olim?", options: ["Nyuton", "Planck", "Faraday", "Amper"], correct: 1, hint: "Maks Planck — 1900 yil, energiya kvantlari." },
        { q: "Massa va og'irlik farqi?", options: ["Bir xil", "Massa kg, og'irlik N (kuch)", "Og'irlik kg, massa N", "Massa = og'irlik × g"], correct: 1, hint: "Og'irlik = m×g (kuch), massa = modda miqdori." },
        { q: "Kompas o'qining shimolga ko'rsatishi sababi?", options: ["Radioaktivlik", "Elektr maydoni", "Yer magnit maydoni", "Tortishish kuchi"], correct: 2, hint: "Yer katta magnitdir." },
        { q: "Lazеr nima?", options: ["Oddiy lampochka", "Bir xil to'lqin uzunligidagi kogerent nur", "Ultrabinafsha nudur", "Rentgen nuri"], correct: 1, hint: "LASER = Light Amplification by Stimulated Emission of Radiation" },
        { q: "Elektr sig'imi birligi?", options: ["Joul", "Volt", "Farad", "Amper"], correct: 2, hint: "Kondensator sig'imi Farad (F) bilan o'lchanadi." },
        { q: "Yadro tuzilmasida proton va neytron umumiy nom?", options: ["Elektron", "Kvark", "Nuklon", "Bozon"], correct: 2, hint: "Proton + neytron = nuklonlar." },
        { q: "Qaysi spektr ko'zga ko'rinmaydi?", options: ["Ko'k nur", "Qizil nur", "Infraqizil", "Sariq"], correct: 2, hint: "Infraqizil > 700nm — ko'rinmas." },
        { q: "Rezonans nima?", options: ["To'lqin qaytarилishi", "Tizimning tabiiy chastotada kuchli tebranishi", "Elektr toki", "Suyuqlik oqimi"], correct: 1, hint: "Majbur chastota = tabiiy chastota → rezonans." },
        { q: "Nisbiylik nazariyasini kim yaratgan?", options: ["Nyuton", "Darvin", "Eynshteyn", "Kyuri"], correct: 2, hint: "Albert Eynshteyn — E=mc² (1905)." },
        { q: "Supero'tkazuvchanlik nima?", options: ["Katta qarshilik", "Nol elektriq qarshilik", "Kuchli magnit maydoni", "Yuqori harorat"], correct: 1, hint: "Supero'tkazgichda R = 0." },
        { q: "Qanday moddalar magnit xususiyatiga ega?", options: ["Barcha metallar", "Temir, nikel, kobalt", "Faqat temir", "Barcha o'tkazgichlar"], correct: 1, hint: "Ferromagnit — Fe, Ni, Co." },
        { q: "Radioaktiv yarim yemirilish davri nima?", options: ["To'liq yemir bo'lish vaqti", "Yarim miqdori yemir bo'lish vaqti", "Reaksiya vaqti", "Atom yorilib ketish vaqti"], correct: 1, hint: "T½ = ham miqdori kamayish vaqti." },
        { q: "Qaysi lens faqat to'plash xususiyatiga ega?", options: ["Botiq (konkav)", "Qavariq (konveks)", "Yassi", "Prizma"], correct: 1, hint: "Konveks linza nurlarni to'playdi." },
        { q: "Elektr quvvati formulasi?", options: ["P = U/I", "P = U×I", "P = I²/R", "P = U×R"], correct: 1, hint: "P = kuchlanish × tok" },
        { q: "Vodorod atomi eng sodda atom — nechtа elektroni bor?", options: ["0", "1", "2", "3"], correct: 1, hint: "H: 1 proton, 1 elektron." },
        { q: "Nurning sinish (refraktsiya) qonuni kim tomonidan aniqlangan?", options: ["Nyuton", "Snell", "Faraday", "Huygens"], correct: 1, hint: "Snell qonuni — sinish burchagi va muhit bog'liqligi." },
        { q: "Elektron mikroskopda nima elektronlarni aniqlaydi?", options: ["Optik linza", "Vakuum trubkasi", "Elektromagnit linza", "Mexanik kamera"], correct: 2, hint: "Elektromagnit maydon elektronlarni yo'naltiradi." },
        { q: "Beta nurlanish nimaligi?", options: ["Fotonlar", "Alfa zarrachalar", "Elektron yoki pozitron", "Neytronlar"], correct: 2, hint: "β = yuqori tezlikli elektron yoki pozitron." },
        { q: "Gravitatsion to'lqinlarni kim kashf etdi (eksperimental)?", options: ["LIGO loyihasi", "NASA", "Eynshteyn", "Nyuton"], correct: 0, hint: "LIGO — 2015 yil birinchi marta aniqladi." },
        { q: "Vaqt bizga qanday tajribada sekinlashadi?", options: ["Past haroratda", "Yuqori tezlik va kuchli gravitatsiyada", "Vakuumda", "Past bosimda"], correct: 1, hint: "Nisbiylik: vaqt dilatatsiyasi." }
    ]
});
